using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AQ1Report.Entities
{
    class clsAQ1ReportHeaderRow
    {
        public int ExcelWorkSheetNo = -1;

        public string Date = "";
        public string PageNo = "";
        public string GeneratedBy = "";
        public string WardName = "";
        public string MeterBinderNo = "";
        public string ReadingCycle = "";
        public string Year = "";

        public clsAQ1ReportHeaderRow(int excelWorkSheetNo)
        {
            ExcelWorkSheetNo = excelWorkSheetNo;
        }

        public void WriteToConsole()
        {
            Console.Write("Excel WorkSheet No: " + this.ExcelWorkSheetNo.ToString() + " | ");

            Console.Write("Date: " + this.Date + ", ");
            Console.Write("Page No: " + this.PageNo + ", ");
            Console.Write("Generated By: " + this.GeneratedBy + ", ");
            Console.Write("Ward Name: " + this.WardName + ", ");
            Console.Write("Meter Binder No: " + this.MeterBinderNo + ", ");
            Console.Write("Reading Cycle: " + this.ReadingCycle + ", ");
            Console.Write("Year: " + this.Year);

            Console.WriteLine("");
        }
    }
}
